/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CartItem {
  'customImageData' : string,
  'quantity' : bigint,
  'selectedSize' : string,
  'product' : ProductInfo,
}
export interface Order {
  'status' : OrderStatus,
  'total' : bigint,
  'paymentStatus' : string,
  'paymentMethod' : string,
  'userId' : Principal,
  'createdAt' : bigint,
  'estimatedDelivery' : string,
  'orderId' : string,
  'shippingAddress' : ShippingAddress,
  'productionFileData' : string,
  'items' : Array<CartItem>,
}
export type OrderStatus = { 'New' : null } |
  { 'Printed' : null } |
  { 'Delivered' : null } |
  { 'Processing' : null } |
  { 'Shipped' : null };
export interface ProductInfo {
  'id' : string,
  'imageData' : string,
  'name' : string,
  'description' : string,
  'dpiSettings' : [] | [bigint],
  'deliveryTime' : string,
  'sizeOptions' : Array<string>,
  'category' : string,
  'price' : bigint,
  'templateImageData' : string,
}
export interface ShippingAddress {
  'city' : string,
  'fullName' : string,
  'state' : string,
  'addressLine1' : string,
  'addressLine2' : string,
  'phone' : string,
  'pincode' : string,
}
export interface Template {
  'id' : string,
  'imageData' : string,
  'name' : string,
  'dpiSettings' : bigint,
  'previewData' : string,
  'photoSlots' : bigint,
}
export interface UserProfile {
  'username' : string,
  'createdAt' : bigint,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  /**
   * / Add a serviceable pincode. Admin only.
   */
  'addPincode' : ActorMethod<[string], undefined>,
  /**
   * / Add a pincode with credentials. Requires caller to be authenticated (#user) AND valid admin credentials.
   */
  'addPincodeWithCredentials' : ActorMethod<
    [string, string, string],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / Assign a role to a user. Admin only (enforced inside AccessControl.assignRole).
   */
  'assignUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / Clear the caller's cart. Requires #user role.
   */
  'clearCart' : ActorMethod<[], undefined>,
  /**
   * / Delete a product. Admin only.
   */
  'deleteProduct' : ActorMethod<[string], undefined>,
  /**
   * / Delete a product with credentials. Requires caller to be authenticated (#user) AND valid admin credentials.
   */
  'deleteProductWithCredentials' : ActorMethod<
    [string, string, string],
    undefined
  >,
  /**
   * / Delete a template. Admin only.
   */
  'deleteTemplate' : ActorMethod<[string], undefined>,
  /**
   * / Delete a template with credentials. Requires caller to be authenticated (#user) AND valid admin credentials.
   */
  'deleteTemplateWithCredentials' : ActorMethod<
    [string, string, string],
    undefined
  >,
  /**
   * / Get all orders. Admin only.
   */
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  /**
   * / Get all orders with credentials. Requires caller to be authenticated (#user) AND valid admin credentials.
   */
  'getAllOrdersWithCredentials' : ActorMethod<[string, string], Array<Order>>,
  /**
   * / Get all available pincodes. Available to everyone.
   */
  'getAvailablePincodes' : ActorMethod<[], Array<string>>,
  /**
   * / Get the caller's own profile. Requires at least #user role.
   */
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / Get the caller's cart. Requires #user role.
   */
  'getCart' : ActorMethod<[], Array<CartItem>>,
  /**
   * / Get the caller's own orders. Requires #user role.
   */
  'getMyOrders' : ActorMethod<[], Array<Order>>,
  /**
   * / Get the role of the caller.
   */
  'getMyRole' : ActorMethod<[], UserRole>,
  /**
   * / Get a specific order. Caller must own the order or be admin.
   */
  'getOrder' : ActorMethod<[string], [] | [Order]>,
  /**
   * / Get payment reference for an order. Caller must own the order or be admin.
   */
  'getPayment' : ActorMethod<[string], [] | [string]>,
  /**
   * / Get a single product by id. Available to everyone.
   */
  'getProduct' : ActorMethod<[string], [] | [ProductInfo]>,
  /**
   * / Get all products. Available to everyone (no auth required).
   */
  'getProducts' : ActorMethod<[], Array<ProductInfo>>,
  /**
   * / Get the caller's saved shipping address. Requires #user role.
   */
  'getShippingAddress' : ActorMethod<[], [] | [ShippingAddress]>,
  /**
   * / Get a single template by id. Available to everyone.
   */
  'getTemplate' : ActorMethod<[string], [] | [Template]>,
  /**
   * / Get all templates. Available to everyone.
   */
  'getTemplates' : ActorMethod<[], Array<Template>>,
  /**
   * / Get any user's profile. Caller may only view their own profile unless admin.
   */
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  /**
   * / Check if a pincode is serviceable. Available to everyone.
   */
  'isPincodeAvailable' : ActorMethod<[string], boolean>,
  /**
   * / Place a new order. Requires #user role.
   */
  'placeOrder' : ActorMethod<[Order], undefined>,
  /**
   * / Record a payment for an order. Requires #user role.
   */
  'recordPayment' : ActorMethod<[string, string], undefined>,
  /**
   * / Remove a serviceable pincode. Admin only.
   */
  'removePincode' : ActorMethod<[string], undefined>,
  /**
   * / Remove a pincode with credentials. Requires caller to be authenticated (#user) AND valid admin credentials.
   */
  'removePincodeWithCredentials' : ActorMethod<
    [string, string, string],
    undefined
  >,
  /**
   * / Save the caller's own profile. Requires at least #user role.
   */
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  /**
   * / Save the caller's cart. Requires #user role.
   */
  'saveCart' : ActorMethod<[Array<CartItem>], undefined>,
  /**
   * / Save the caller's shipping address. Requires #user role.
   */
  'saveShippingAddress' : ActorMethod<[ShippingAddress], undefined>,
  /**
   * / Update order status. Admin only.
   */
  'updateOrderStatus' : ActorMethod<[string, OrderStatus], undefined>,
  /**
   * / Update order status with credentials. Requires caller to be authenticated (#user) AND valid admin credentials.
   */
  'updateOrderStatusWithCredentials' : ActorMethod<
    [string, string, string, OrderStatus],
    undefined
  >,
  /**
   * / Add or update a product. Admin only.
   */
  'upsertProduct' : ActorMethod<[ProductInfo], undefined>,
  /**
   * / Add or update a product with credentials. Requires caller to be authenticated (#user) AND valid admin credentials.
   */
  'upsertProductWithCredentials' : ActorMethod<
    [string, string, ProductInfo],
    undefined
  >,
  /**
   * / Add or update a template. Admin only.
   */
  'upsertTemplate' : ActorMethod<[Template], undefined>,
  /**
   * / Add or update a template with credentials. Requires caller to be authenticated (#user) AND valid admin credentials.
   */
  'upsertTemplateWithCredentials' : ActorMethod<
    [string, string, Template],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];