/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const OrderStatus = IDL.Variant({
  'New' : IDL.Null,
  'Printed' : IDL.Null,
  'Delivered' : IDL.Null,
  'Processing' : IDL.Null,
  'Shipped' : IDL.Null,
});
export const ShippingAddress = IDL.Record({
  'city' : IDL.Text,
  'fullName' : IDL.Text,
  'state' : IDL.Text,
  'addressLine1' : IDL.Text,
  'addressLine2' : IDL.Text,
  'phone' : IDL.Text,
  'pincode' : IDL.Text,
});
export const ProductInfo = IDL.Record({
  'id' : IDL.Text,
  'imageData' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'dpiSettings' : IDL.Opt(IDL.Nat),
  'deliveryTime' : IDL.Text,
  'sizeOptions' : IDL.Vec(IDL.Text),
  'category' : IDL.Text,
  'price' : IDL.Nat,
  'templateImageData' : IDL.Text,
});
export const CartItem = IDL.Record({
  'customImageData' : IDL.Text,
  'quantity' : IDL.Nat,
  'selectedSize' : IDL.Text,
  'product' : ProductInfo,
});
export const Order = IDL.Record({
  'status' : OrderStatus,
  'total' : IDL.Nat,
  'paymentStatus' : IDL.Text,
  'paymentMethod' : IDL.Text,
  'userId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'estimatedDelivery' : IDL.Text,
  'orderId' : IDL.Text,
  'shippingAddress' : ShippingAddress,
  'productionFileData' : IDL.Text,
  'items' : IDL.Vec(CartItem),
});
export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'createdAt' : IDL.Int,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const Template = IDL.Record({
  'id' : IDL.Text,
  'imageData' : IDL.Text,
  'name' : IDL.Text,
  'dpiSettings' : IDL.Nat,
  'previewData' : IDL.Text,
  'photoSlots' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addPincode' : IDL.Func([IDL.Text], [], []),
  'addPincodeWithCredentials' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearCart' : IDL.Func([], [], []),
  'deleteProduct' : IDL.Func([IDL.Text], [], []),
  'deleteProductWithCredentials' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'deleteTemplate' : IDL.Func([IDL.Text], [], []),
  'deleteTemplateWithCredentials' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getAllOrdersWithCredentials' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(Order)],
      [],
    ),
  'getAvailablePincodes' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
  'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getMyRole' : IDL.Func([], [UserRole], ['query']),
  'getOrder' : IDL.Func([IDL.Text], [IDL.Opt(Order)], ['query']),
  'getPayment' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
  'getProduct' : IDL.Func([IDL.Text], [IDL.Opt(ProductInfo)], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(ProductInfo)], ['query']),
  'getShippingAddress' : IDL.Func([], [IDL.Opt(ShippingAddress)], ['query']),
  'getTemplate' : IDL.Func([IDL.Text], [IDL.Opt(Template)], ['query']),
  'getTemplates' : IDL.Func([], [IDL.Vec(Template)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isPincodeAvailable' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'placeOrder' : IDL.Func([Order], [], []),
  'recordPayment' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'removePincode' : IDL.Func([IDL.Text], [], []),
  'removePincodeWithCredentials' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveCart' : IDL.Func([IDL.Vec(CartItem)], [], []),
  'saveShippingAddress' : IDL.Func([ShippingAddress], [], []),
  'updateOrderStatus' : IDL.Func([IDL.Text, OrderStatus], [], []),
  'updateOrderStatusWithCredentials' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, OrderStatus],
      [],
      [],
    ),
  'upsertProduct' : IDL.Func([ProductInfo], [], []),
  'upsertProductWithCredentials' : IDL.Func(
      [IDL.Text, IDL.Text, ProductInfo],
      [],
      [],
    ),
  'upsertTemplate' : IDL.Func([Template], [], []),
  'upsertTemplateWithCredentials' : IDL.Func(
      [IDL.Text, IDL.Text, Template],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const OrderStatus = IDL.Variant({
    'New' : IDL.Null,
    'Printed' : IDL.Null,
    'Delivered' : IDL.Null,
    'Processing' : IDL.Null,
    'Shipped' : IDL.Null,
  });
  const ShippingAddress = IDL.Record({
    'city' : IDL.Text,
    'fullName' : IDL.Text,
    'state' : IDL.Text,
    'addressLine1' : IDL.Text,
    'addressLine2' : IDL.Text,
    'phone' : IDL.Text,
    'pincode' : IDL.Text,
  });
  const ProductInfo = IDL.Record({
    'id' : IDL.Text,
    'imageData' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'dpiSettings' : IDL.Opt(IDL.Nat),
    'deliveryTime' : IDL.Text,
    'sizeOptions' : IDL.Vec(IDL.Text),
    'category' : IDL.Text,
    'price' : IDL.Nat,
    'templateImageData' : IDL.Text,
  });
  const CartItem = IDL.Record({
    'customImageData' : IDL.Text,
    'quantity' : IDL.Nat,
    'selectedSize' : IDL.Text,
    'product' : ProductInfo,
  });
  const Order = IDL.Record({
    'status' : OrderStatus,
    'total' : IDL.Nat,
    'paymentStatus' : IDL.Text,
    'paymentMethod' : IDL.Text,
    'userId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'estimatedDelivery' : IDL.Text,
    'orderId' : IDL.Text,
    'shippingAddress' : ShippingAddress,
    'productionFileData' : IDL.Text,
    'items' : IDL.Vec(CartItem),
  });
  const UserProfile = IDL.Record({
    'username' : IDL.Text,
    'createdAt' : IDL.Int,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Template = IDL.Record({
    'id' : IDL.Text,
    'imageData' : IDL.Text,
    'name' : IDL.Text,
    'dpiSettings' : IDL.Nat,
    'previewData' : IDL.Text,
    'photoSlots' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addPincode' : IDL.Func([IDL.Text], [], []),
    'addPincodeWithCredentials' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearCart' : IDL.Func([], [], []),
    'deleteProduct' : IDL.Func([IDL.Text], [], []),
    'deleteProductWithCredentials' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'deleteTemplate' : IDL.Func([IDL.Text], [], []),
    'deleteTemplateWithCredentials' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getAllOrdersWithCredentials' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(Order)],
        [],
      ),
    'getAvailablePincodes' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
    'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getMyRole' : IDL.Func([], [UserRole], ['query']),
    'getOrder' : IDL.Func([IDL.Text], [IDL.Opt(Order)], ['query']),
    'getPayment' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
    'getProduct' : IDL.Func([IDL.Text], [IDL.Opt(ProductInfo)], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(ProductInfo)], ['query']),
    'getShippingAddress' : IDL.Func([], [IDL.Opt(ShippingAddress)], ['query']),
    'getTemplate' : IDL.Func([IDL.Text], [IDL.Opt(Template)], ['query']),
    'getTemplates' : IDL.Func([], [IDL.Vec(Template)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isPincodeAvailable' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'placeOrder' : IDL.Func([Order], [], []),
    'recordPayment' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'removePincode' : IDL.Func([IDL.Text], [], []),
    'removePincodeWithCredentials' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveCart' : IDL.Func([IDL.Vec(CartItem)], [], []),
    'saveShippingAddress' : IDL.Func([ShippingAddress], [], []),
    'updateOrderStatus' : IDL.Func([IDL.Text, OrderStatus], [], []),
    'updateOrderStatusWithCredentials' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, OrderStatus],
        [],
        [],
      ),
    'upsertProduct' : IDL.Func([ProductInfo], [], []),
    'upsertProductWithCredentials' : IDL.Func(
        [IDL.Text, IDL.Text, ProductInfo],
        [],
        [],
      ),
    'upsertTemplate' : IDL.Func([Template], [], []),
    'upsertTemplateWithCredentials' : IDL.Func(
        [IDL.Text, IDL.Text, Template],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };