/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ProductInfo = IDL.Record({
  'id' : IDL.Text,
  'imageData' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'dpiSettings' : IDL.Nat,
  'deliveryTime' : IDL.Text,
  'sizeOptions' : IDL.Vec(IDL.Text),
  'category' : IDL.Text,
  'price' : IDL.Float64,
  'templateImageData' : IDL.Text,
});
export const Template = IDL.Record({
  'id' : IDL.Text,
  'imageData' : IDL.Text,
  'name' : IDL.Text,
  'dpiSettings' : IDL.Nat,
  'previewData' : IDL.Text,
  'photoSlots' : IDL.Nat,
});
export const CartItem = IDL.Record({
  'customImageData' : IDL.Text,
  'quantity' : IDL.Nat,
  'selectedSize' : IDL.Text,
  'product' : ProductInfo,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShippingAddress = IDL.Record({
  'city' : IDL.Text,
  'fullName' : IDL.Text,
  'state' : IDL.Text,
  'addressLine1' : IDL.Text,
  'addressLine2' : IDL.Text,
  'phone' : IDL.Text,
  'pincode' : IDL.Text,
});
export const OrderStatus = IDL.Variant({
  'New' : IDL.Null,
  'Printed' : IDL.Null,
  'Delivered' : IDL.Null,
  'Processing' : IDL.Null,
  'Shipped' : IDL.Null,
});
export const Order = IDL.Record({
  'status' : OrderStatus,
  'total' : IDL.Float64,
  'paymentStatus' : IDL.Text,
  'paymentMethod' : IDL.Text,
  'userId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'estimatedDelivery' : IDL.Text,
  'orderId' : IDL.Text,
  'shippingAddress' : ShippingAddress,
  'productionFileData' : IDL.Text,
  'items' : IDL.Vec(CartItem),
});
export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'createdAt' : IDL.Int,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addOrUpdateProduct' : IDL.Func([ProductInfo], [], []),
  'addOrUpdateTemplate' : IDL.Func([Template], [], []),
  'addPincode' : IDL.Func([IDL.Text], [], []),
  'addToCart' : IDL.Func([CartItem], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearCart' : IDL.Func([], [], []),
  'createOrder' : IDL.Func([IDL.Text, ShippingAddress], [IDL.Text], []),
  'createProduct' : IDL.Func([ProductInfo], [], []),
  'createTemplate' : IDL.Func([Template], [], []),
  'deleteProduct' : IDL.Func([IDL.Text], [], []),
  'deleteTemplate' : IDL.Func([IDL.Text], [], []),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(ProductInfo)], ['query']),
  'getAllTemplates' : IDL.Func([], [IDL.Vec(Template)], ['query']),
  'getAllUsers' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
  'getDashboardSummary' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalProducts' : IDL.Nat,
          'totalOrders' : IDL.Nat,
          'totalUsers' : IDL.Nat,
          'totalEarnings' : IDL.Float64,
        }),
      ],
      ['query'],
    ),
  'getMyAddress' : IDL.Func([], [IDL.Opt(ShippingAddress)], ['query']),
  'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getProduct' : IDL.Func([IDL.Text], [IDL.Opt(ProductInfo)], ['query']),
  'getProductsByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ProductInfo)],
      ['query'],
    ),
  'getSelectedSize' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getTemplate' : IDL.Func([IDL.Text], [IDL.Opt(Template)], ['query']),
  'getUserOrderHistory' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Order)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isPincodeAvailable' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'login' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'logout' : IDL.Func([], [], []),
  'removeFromCart' : IDL.Func([IDL.Text], [], []),
  'removePincode' : IDL.Func([IDL.Text], [], []),
  'saveAddress' : IDL.Func([ShippingAddress], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'selectSize' : IDL.Func([IDL.Text], [], []),
  'setProductionFileData' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'trackOrder' : IDL.Func([IDL.Text], [Order], ['query']),
  'updateOrderStatus' : IDL.Func([IDL.Text, OrderStatus], [], []),
  'updateProduct' : IDL.Func([ProductInfo], [], []),
  'updateTemplate' : IDL.Func([Template], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ProductInfo = IDL.Record({
    'id' : IDL.Text,
    'imageData' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'dpiSettings' : IDL.Nat,
    'deliveryTime' : IDL.Text,
    'sizeOptions' : IDL.Vec(IDL.Text),
    'category' : IDL.Text,
    'price' : IDL.Float64,
    'templateImageData' : IDL.Text,
  });
  const Template = IDL.Record({
    'id' : IDL.Text,
    'imageData' : IDL.Text,
    'name' : IDL.Text,
    'dpiSettings' : IDL.Nat,
    'previewData' : IDL.Text,
    'photoSlots' : IDL.Nat,
  });
  const CartItem = IDL.Record({
    'customImageData' : IDL.Text,
    'quantity' : IDL.Nat,
    'selectedSize' : IDL.Text,
    'product' : ProductInfo,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShippingAddress = IDL.Record({
    'city' : IDL.Text,
    'fullName' : IDL.Text,
    'state' : IDL.Text,
    'addressLine1' : IDL.Text,
    'addressLine2' : IDL.Text,
    'phone' : IDL.Text,
    'pincode' : IDL.Text,
  });
  const OrderStatus = IDL.Variant({
    'New' : IDL.Null,
    'Printed' : IDL.Null,
    'Delivered' : IDL.Null,
    'Processing' : IDL.Null,
    'Shipped' : IDL.Null,
  });
  const Order = IDL.Record({
    'status' : OrderStatus,
    'total' : IDL.Float64,
    'paymentStatus' : IDL.Text,
    'paymentMethod' : IDL.Text,
    'userId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'estimatedDelivery' : IDL.Text,
    'orderId' : IDL.Text,
    'shippingAddress' : ShippingAddress,
    'productionFileData' : IDL.Text,
    'items' : IDL.Vec(CartItem),
  });
  const UserProfile = IDL.Record({
    'username' : IDL.Text,
    'createdAt' : IDL.Int,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addOrUpdateProduct' : IDL.Func([ProductInfo], [], []),
    'addOrUpdateTemplate' : IDL.Func([Template], [], []),
    'addPincode' : IDL.Func([IDL.Text], [], []),
    'addToCart' : IDL.Func([CartItem], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearCart' : IDL.Func([], [], []),
    'createOrder' : IDL.Func([IDL.Text, ShippingAddress], [IDL.Text], []),
    'createProduct' : IDL.Func([ProductInfo], [], []),
    'createTemplate' : IDL.Func([Template], [], []),
    'deleteProduct' : IDL.Func([IDL.Text], [], []),
    'deleteTemplate' : IDL.Func([IDL.Text], [], []),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(ProductInfo)], ['query']),
    'getAllTemplates' : IDL.Func([], [IDL.Vec(Template)], ['query']),
    'getAllUsers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
    'getDashboardSummary' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalProducts' : IDL.Nat,
            'totalOrders' : IDL.Nat,
            'totalUsers' : IDL.Nat,
            'totalEarnings' : IDL.Float64,
          }),
        ],
        ['query'],
      ),
    'getMyAddress' : IDL.Func([], [IDL.Opt(ShippingAddress)], ['query']),
    'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getProduct' : IDL.Func([IDL.Text], [IDL.Opt(ProductInfo)], ['query']),
    'getProductsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ProductInfo)],
        ['query'],
      ),
    'getSelectedSize' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getTemplate' : IDL.Func([IDL.Text], [IDL.Opt(Template)], ['query']),
    'getUserOrderHistory' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Order)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isPincodeAvailable' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'login' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'logout' : IDL.Func([], [], []),
    'removeFromCart' : IDL.Func([IDL.Text], [], []),
    'removePincode' : IDL.Func([IDL.Text], [], []),
    'saveAddress' : IDL.Func([ShippingAddress], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'selectSize' : IDL.Func([IDL.Text], [], []),
    'setProductionFileData' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'trackOrder' : IDL.Func([IDL.Text], [Order], ['query']),
    'updateOrderStatus' : IDL.Func([IDL.Text, OrderStatus], [], []),
    'updateProduct' : IDL.Func([ProductInfo], [], []),
    'updateTemplate' : IDL.Func([Template], [], []),
  });
};

export const init = ({ IDL }) => { return []; };