/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CartItem {
  'customImageData' : string,
  'quantity' : bigint,
  'selectedSize' : string,
  'product' : ProductInfo,
}
export interface Order {
  'status' : OrderStatus,
  'total' : number,
  'paymentStatus' : string,
  'paymentMethod' : string,
  'userId' : Principal,
  'createdAt' : bigint,
  'estimatedDelivery' : string,
  'orderId' : string,
  'shippingAddress' : ShippingAddress,
  'productionFileData' : string,
  'items' : Array<CartItem>,
}
export type OrderStatus = { 'New' : null } |
  { 'Printed' : null } |
  { 'Delivered' : null } |
  { 'Processing' : null } |
  { 'Shipped' : null };
export interface ProductInfo {
  'id' : string,
  'imageData' : string,
  'name' : string,
  'description' : string,
  'dpiSettings' : bigint,
  'deliveryTime' : string,
  'sizeOptions' : Array<string>,
  'category' : string,
  'price' : number,
  'templateImageData' : string,
}
export interface ShippingAddress {
  'city' : string,
  'fullName' : string,
  'state' : string,
  'addressLine1' : string,
  'addressLine2' : string,
  'phone' : string,
  'pincode' : string,
}
export interface Template {
  'id' : string,
  'imageData' : string,
  'name' : string,
  'dpiSettings' : bigint,
  'previewData' : string,
  'photoSlots' : bigint,
}
export interface UserProfile {
  'username' : string,
  'createdAt' : bigint,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addOrUpdateProduct' : ActorMethod<[ProductInfo], undefined>,
  'addOrUpdateTemplate' : ActorMethod<[Template], undefined>,
  'addPincode' : ActorMethod<[string], undefined>,
  'addToCart' : ActorMethod<[CartItem], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearCart' : ActorMethod<[], undefined>,
  'createOrder' : ActorMethod<[string, ShippingAddress], string>,
  'deleteProduct' : ActorMethod<[string], undefined>,
  'deleteTemplate' : ActorMethod<[string], undefined>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllProducts' : ActorMethod<[], Array<ProductInfo>>,
  'getAllTemplates' : ActorMethod<[], Array<Template>>,
  'getAllUsers' : ActorMethod<[], Array<[Principal, UserProfile]>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCart' : ActorMethod<[], Array<CartItem>>,
  'getDashboardSummary' : ActorMethod<
    [],
    {
      'totalProducts' : bigint,
      'totalOrders' : bigint,
      'totalUsers' : bigint,
      'totalEarnings' : number,
    }
  >,
  'getMyAddress' : ActorMethod<[], [] | [ShippingAddress]>,
  'getMyOrders' : ActorMethod<[], Array<Order>>,
  'getProduct' : ActorMethod<[string], [] | [ProductInfo]>,
  'getProductsByCategory' : ActorMethod<[string], Array<ProductInfo>>,
  'getSelectedSize' : ActorMethod<[], [] | [string]>,
  'getTemplate' : ActorMethod<[string], [] | [Template]>,
  'getUserOrderHistory' : ActorMethod<[Principal], Array<Order>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isPincodeAvailable' : ActorMethod<[string], boolean>,
  'removeFromCart' : ActorMethod<[string], undefined>,
  'removePincode' : ActorMethod<[string], undefined>,
  'saveAddress' : ActorMethod<[ShippingAddress], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'selectSize' : ActorMethod<[string], undefined>,
  'setProductionFileData' : ActorMethod<[string, string], undefined>,
  'trackOrder' : ActorMethod<[string], Order>,
  'updateOrderStatus' : ActorMethod<[string, OrderStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];