import type { ProductInfo } from '../backend';

export const demoProducts: (ProductInfo & { dpiSettings: bigint })[] = [
  // Photo Prints
  {
    id: 'demo-print-1',
    name: 'Classic Art Print',
    price: 349,
    category: 'Photo Prints',
    imageData: '/assets/generated/photo-print-1.dim_600x600.png',
    templateImageData: '',
    description: 'Flat art print mounted beautifully — perfect for living rooms and galleries',
    sizeOptions: ['4x6', '5x7', '8x10', '12x18'],
    deliveryTime: '2-4 days',
    dpiSettings: BigInt(300),
  },
  {
    id: 'demo-print-2',
    name: 'Colorful Collage Print',
    price: 449,
    category: 'Photo Prints',
    imageData: '/assets/generated/photo-print-2.dim_600x600.png',
    templateImageData: '',
    description: 'Vibrant collage art print on premium textured paper',
    sizeOptions: ['8x10', '12x16', '16x20'],
    deliveryTime: '2-4 days',
    dpiSettings: BigInt(300),
  },
  {
    id: 'demo-print-3',
    name: 'Minimalist Landscape Poster',
    price: 499,
    category: 'Photo Prints',
    imageData: '/assets/generated/photo-print-3.dim_600x600.png',
    templateImageData: '',
    description: 'Minimalist landscape poster print — clean, modern, and elegant',
    sizeOptions: ['12x18', '18x24', '24x36'],
    deliveryTime: '2-4 days',
    dpiSettings: BigInt(300),
  },

  // Photo Frames
  {
    id: 'demo-frame-1',
    name: 'Classic Wood Photo Frame',
    price: 599,
    category: 'Photo Frames',
    imageData: '/assets/generated/photo-frame-1.dim_600x600.png',
    templateImageData: '',
    description: 'Dark wooden photo frame — perfect for family portraits on shelves',
    sizeOptions: ['4x6', '5x7', '8x10'],
    deliveryTime: '3-5 days',
    dpiSettings: BigInt(300),
  },
  {
    id: 'demo-frame-2',
    name: 'Black Wall Photo Frame',
    price: 699,
    category: 'Photo Frames',
    imageData: '/assets/generated/photo-frame-2.dim_600x600.png',
    templateImageData: '',
    description: 'Sleek black photo frame for wall display — ideal for couple portraits',
    sizeOptions: ['5x7', '8x10', '12x16'],
    deliveryTime: '3-5 days',
    dpiSettings: BigInt(300),
  },
  {
    id: 'demo-frame-3',
    name: 'Gold Ornate Photo Frame',
    price: 899,
    category: 'Photo Frames',
    imageData: '/assets/generated/photo-frame-3.dim_600x600.png',
    templateImageData: '',
    description: 'Elegant gold-finish ornate frame — a timeless keepsake for baby portraits',
    sizeOptions: ['4x6', '5x7', '8x10'],
    deliveryTime: '3-5 days',
    dpiSettings: BigInt(300),
  },

  // Photo Magnets
  {
    id: 'demo-magnet-1',
    name: 'Square Photo Magnet',
    price: 199,
    category: 'Photo Magnets',
    imageData: '/assets/generated/photo-magnet-1.dim_600x600.png',
    templateImageData: '',
    description: 'Square refrigerator magnet with your favorite family photo printed on it',
    sizeOptions: ['2x2', '3x3', '4x4'],
    deliveryTime: '2-4 days',
    dpiSettings: BigInt(300),
  },
  {
    id: 'demo-magnet-2',
    name: 'Round Photo Magnet Set',
    price: 299,
    category: 'Photo Magnets',
    imageData: '/assets/generated/photo-magnet-2.dim_600x600.png',
    templateImageData: '',
    description: 'Set of three round photo magnets — great for portraits and memories',
    sizeOptions: ['2-inch', '3-inch'],
    deliveryTime: '2-4 days',
    dpiSettings: BigInt(300),
  },
  {
    id: 'demo-magnet-3',
    name: 'Heart-Shaped Photo Magnet',
    price: 249,
    category: 'Photo Magnets',
    imageData: '/assets/generated/photo-magnet-3.dim_600x600.png',
    templateImageData: '',
    description: 'Heart-shaped photo magnet — a sweet gift for couples and loved ones',
    sizeOptions: ['3-inch', '4-inch'],
    deliveryTime: '2-4 days',
    dpiSettings: BigInt(300),
  },

  // Mugs
  {
    id: 'demo-mug-1',
    name: 'Custom Family Photo Mug',
    price: 399,
    category: 'Mugs',
    imageData: '/assets/generated/mug-1.dim_600x600.png',
    templateImageData: '',
    description: 'White ceramic mug with your custom family photo — start every day with a smile',
    sizeOptions: ['11oz', '15oz'],
    deliveryTime: '3-5 days',
    dpiSettings: BigInt(300),
  },
  {
    id: 'demo-mug-2',
    name: 'Landscape Travel Mug',
    price: 499,
    category: 'Mugs',
    imageData: '/assets/generated/mug-2.dim_600x600.png',
    templateImageData: '',
    description: 'White ceramic travel mug with a stunning landscape photo print',
    sizeOptions: ['11oz', '15oz'],
    deliveryTime: '3-5 days',
    dpiSettings: BigInt(300),
  },
  {
    id: 'demo-mug-3',
    name: 'Couple Matching Mugs',
    price: 749,
    category: 'Mugs',
    imageData: '/assets/generated/mug-3.dim_600x600.png',
    templateImageData: '',
    description: 'Pair of white mugs with matching couple photo prints — perfect gift for two',
    sizeOptions: ['11oz', '15oz'],
    deliveryTime: '3-5 days',
    dpiSettings: BigInt(300),
  },

  // Corporate Gifts
  {
    id: 'demo-corp-1',
    name: 'Corporate Branded Gift Set',
    price: 1299,
    category: 'Corporate Gifts',
    imageData: '/assets/generated/corporate-gift-1.dim_600x600.png',
    templateImageData: '',
    description: 'Premium corporate gift set with branded mug, notepad, and pen',
    sizeOptions: ['Standard', 'Premium'],
    deliveryTime: '5-7 days',
    dpiSettings: BigInt(300),
  },
  {
    id: 'demo-corp-2',
    name: 'Custom Desk Calendar',
    price: 799,
    category: 'Corporate Gifts',
    imageData: '/assets/generated/corporate-gift-2.dim_600x600.png',
    templateImageData: '',
    description: 'Customized corporate desk calendar with your company logo and branding',
    sizeOptions: ['A4', 'A5'],
    deliveryTime: '5-7 days',
    dpiSettings: BigInt(300),
  },
  {
    id: 'demo-corp-3',
    name: 'Branded Corporate Tote Bag',
    price: 599,
    category: 'Corporate Gifts',
    imageData: '/assets/generated/corporate-gift-3.dim_600x600.png',
    templateImageData: '',
    description: 'Branded corporate tote bag with printed logo and name — stylish and practical',
    sizeOptions: ['Standard', 'Large'],
    deliveryTime: '5-7 days',
    dpiSettings: BigInt(300),
  },
];

export function getDemoProductById(id: string): (ProductInfo & { dpiSettings: bigint }) | undefined {
  return demoProducts.find((p) => p.id === id);
}
