/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface ProductInfo {
    id: string;
    imageData: string;
    name: string;
    description: string;
    dpiSettings?: bigint;
    deliveryTime: string;
    sizeOptions: Array<string>;
    category: string;
    price: bigint;
    templateImageData: string;
}
export interface ShippingAddress {
    city: string;
    fullName: string;
    state: string;
    addressLine1: string;
    addressLine2: string;
    phone: string;
    pincode: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface CartItem {
    customImageData: string;
    quantity: bigint;
    selectedSize: string;
    product: ProductInfo;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Order {
    status: OrderStatus;
    total: bigint;
    paymentStatus: string;
    paymentMethod: string;
    userId: Principal;
    createdAt: bigint;
    estimatedDelivery: string;
    orderId: string;
    shippingAddress: ShippingAddress;
    productionFileData: string;
    items: Array<CartItem>;
}
export interface UserProfile {
    username: string;
    createdAt: bigint;
    email: string;
    phone: string;
}
export interface Template {
    id: string;
    imageData: string;
    name: string;
    dpiSettings: bigint;
    previewData: string;
    photoSlots: bigint;
}
export enum OrderStatus {
    New = "New",
    Printed = "Printed",
    Delivered = "Delivered",
    Processing = "Processing",
    Shipped = "Shipped"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    /**
     * / Add a serviceable pincode. Admin only.
     */
    addPincode(pincode: string): Promise<void>;
    /**
     * / Add a pincode with credentials. Requires caller to be authenticated (#user) AND valid admin credentials.
     */
    addPincodeWithCredentials(adminUser: string, adminPass: string, pincode: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    /**
     * / Assign a role to a user. Admin only (enforced inside AccessControl.assignRole).
     */
    assignUserRole(user: Principal, role: UserRole): Promise<void>;
    /**
     * / Clear the caller's cart. Requires #user role.
     */
    clearCart(): Promise<void>;
    /**
     * / Delete a product. Admin only.
     */
    deleteProduct(id: string): Promise<void>;
    /**
     * / Delete a product with credentials. Requires caller to be authenticated (#user) AND valid admin credentials.
     */
    deleteProductWithCredentials(adminUser: string, adminPass: string, id: string): Promise<void>;
    /**
     * / Delete a template. Admin only.
     */
    deleteTemplate(id: string): Promise<void>;
    /**
     * / Delete a template with credentials. Requires caller to be authenticated (#user) AND valid admin credentials.
     */
    deleteTemplateWithCredentials(adminUser: string, adminPass: string, id: string): Promise<void>;
    /**
     * / Get all orders. Admin only.
     */
    getAllOrders(): Promise<Array<Order>>;
    /**
     * / Get all orders with credentials. Requires caller to be authenticated (#user) AND valid admin credentials.
     */
    getAllOrdersWithCredentials(adminUser: string, adminPass: string): Promise<Array<Order>>;
    /**
     * / Get all available pincodes. Available to everyone.
     */
    getAvailablePincodes(): Promise<Array<string>>;
    /**
     * / Get the caller's own profile. Requires at least #user role.
     */
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    /**
     * / Get the caller's cart. Requires #user role.
     */
    getCart(): Promise<Array<CartItem>>;
    /**
     * / Get the caller's own orders. Requires #user role.
     */
    getMyOrders(): Promise<Array<Order>>;
    /**
     * / Get the role of the caller.
     */
    getMyRole(): Promise<UserRole>;
    /**
     * / Get a specific order. Caller must own the order or be admin.
     */
    getOrder(orderId: string): Promise<Order | null>;
    /**
     * / Get payment reference for an order. Caller must own the order or be admin.
     */
    getPayment(orderId: string): Promise<string | null>;
    /**
     * / Get a single product by id. Available to everyone.
     */
    getProduct(id: string): Promise<ProductInfo | null>;
    /**
     * / Get all products. Available to everyone (no auth required).
     */
    getProducts(): Promise<Array<ProductInfo>>;
    /**
     * / Get the caller's saved shipping address. Requires #user role.
     */
    getShippingAddress(): Promise<ShippingAddress | null>;
    /**
     * / Get a single template by id. Available to everyone.
     */
    getTemplate(id: string): Promise<Template | null>;
    /**
     * / Get all templates. Available to everyone.
     */
    getTemplates(): Promise<Array<Template>>;
    /**
     * / Get any user's profile. Caller may only view their own profile unless admin.
     */
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    /**
     * / Check if a pincode is serviceable. Available to everyone.
     */
    isPincodeAvailable(pincode: string): Promise<boolean>;
    /**
     * / Place a new order. Requires #user role.
     */
    placeOrder(order: Order): Promise<void>;
    /**
     * / Record a payment for an order. Requires #user role.
     */
    recordPayment(orderId: string, paymentRef: string): Promise<void>;
    /**
     * / Remove a serviceable pincode. Admin only.
     */
    removePincode(pincode: string): Promise<void>;
    /**
     * / Remove a pincode with credentials. Requires caller to be authenticated (#user) AND valid admin credentials.
     */
    removePincodeWithCredentials(adminUser: string, adminPass: string, pincode: string): Promise<void>;
    /**
     * / Save the caller's own profile. Requires at least #user role.
     */
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    /**
     * / Save the caller's cart. Requires #user role.
     */
    saveCart(items: Array<CartItem>): Promise<void>;
    /**
     * / Save the caller's shipping address. Requires #user role.
     */
    saveShippingAddress(address: ShippingAddress): Promise<void>;
    /**
     * / Update order status. Admin only.
     */
    updateOrderStatus(orderId: string, status: OrderStatus): Promise<void>;
    /**
     * / Update order status with credentials. Requires caller to be authenticated (#user) AND valid admin credentials.
     */
    updateOrderStatusWithCredentials(adminUser: string, adminPass: string, orderId: string, status: OrderStatus): Promise<void>;
    /**
     * / Add or update a product. Admin only.
     */
    upsertProduct(product: ProductInfo): Promise<void>;
    /**
     * / Add or update a product with credentials. Requires caller to be authenticated (#user) AND valid admin credentials.
     */
    upsertProductWithCredentials(adminUser: string, adminPass: string, product: ProductInfo): Promise<void>;
    /**
     * / Add or update a template. Admin only.
     */
    upsertTemplate(template: Template): Promise<void>;
    /**
     * / Add or update a template with credentials. Requires caller to be authenticated (#user) AND valid admin credentials.
     */
    upsertTemplateWithCredentials(adminUser: string, adminPass: string, template: Template): Promise<void>;
}
import type { CartItem as _CartItem, Order as _Order, OrderStatus as _OrderStatus, ProductInfo as _ProductInfo, ShippingAddress as _ShippingAddress, Template as _Template, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addPincode(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addPincode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPincode(arg0);
            return result;
        }
    }
    async addPincodeWithCredentials(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addPincodeWithCredentials(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPincodeWithCredentials(arg0, arg1, arg2);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async clearCart(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearCart();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearCart();
            return result;
        }
    }
    async deleteProduct(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProduct(arg0);
            return result;
        }
    }
    async deleteProductWithCredentials(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProductWithCredentials(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProductWithCredentials(arg0, arg1, arg2);
            return result;
        }
    }
    async deleteTemplate(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTemplate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTemplate(arg0);
            return result;
        }
    }
    async deleteTemplateWithCredentials(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTemplateWithCredentials(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTemplateWithCredentials(arg0, arg1, arg2);
            return result;
        }
    }
    async getAllOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllOrders();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllOrders();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllOrdersWithCredentials(arg0: string, arg1: string): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllOrdersWithCredentials(arg0, arg1);
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllOrdersWithCredentials(arg0, arg1);
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAvailablePincodes(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailablePincodes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailablePincodes();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCart(): Promise<Array<CartItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCart();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCart();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyOrders();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyOrders();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyRole();
                return from_candid_UserRole_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyRole();
            return from_candid_UserRole_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrder(arg0: string): Promise<Order | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrder(arg0);
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrder(arg0);
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPayment(arg0: string): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPayment(arg0);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPayment(arg0);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProduct(arg0: string): Promise<ProductInfo | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProduct(arg0);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProduct(arg0);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProducts(): Promise<Array<ProductInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProducts();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProducts();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getShippingAddress(): Promise<ShippingAddress | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getShippingAddress();
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getShippingAddress();
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTemplate(arg0: string): Promise<Template | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTemplate(arg0);
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTemplate(arg0);
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTemplates(): Promise<Array<Template>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTemplates();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTemplates();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isPincodeAvailable(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isPincodeAvailable(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isPincodeAvailable(arg0);
            return result;
        }
    }
    async placeOrder(arg0: Order): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.placeOrder(to_candid_Order_n29(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.placeOrder(to_candid_Order_n29(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async recordPayment(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordPayment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordPayment(arg0, arg1);
            return result;
        }
    }
    async removePincode(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removePincode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removePincode(arg0);
            return result;
        }
    }
    async removePincodeWithCredentials(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removePincodeWithCredentials(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removePincodeWithCredentials(arg0, arg1, arg2);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async saveCart(arg0: Array<CartItem>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCart(to_candid_vec_n33(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCart(to_candid_vec_n33(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveShippingAddress(arg0: ShippingAddress): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveShippingAddress(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveShippingAddress(arg0);
            return result;
        }
    }
    async updateOrderStatus(arg0: string, arg1: OrderStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n31(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n31(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateOrderStatusWithCredentials(arg0: string, arg1: string, arg2: string, arg3: OrderStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrderStatusWithCredentials(arg0, arg1, arg2, to_candid_OrderStatus_n31(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrderStatusWithCredentials(arg0, arg1, arg2, to_candid_OrderStatus_n31(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async upsertProduct(arg0: ProductInfo): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.upsertProduct(to_candid_ProductInfo_n36(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.upsertProduct(to_candid_ProductInfo_n36(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async upsertProductWithCredentials(arg0: string, arg1: string, arg2: ProductInfo): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.upsertProductWithCredentials(arg0, arg1, to_candid_ProductInfo_n36(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.upsertProductWithCredentials(arg0, arg1, to_candid_ProductInfo_n36(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async upsertTemplate(arg0: Template): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.upsertTemplate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.upsertTemplate(arg0);
            return result;
        }
    }
    async upsertTemplateWithCredentials(arg0: string, arg1: string, arg2: Template): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.upsertTemplateWithCredentials(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.upsertTemplateWithCredentials(arg0, arg1, arg2);
            return result;
        }
    }
}
function from_candid_CartItem_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CartItem): CartItem {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_OrderStatus_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Order_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Order {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_ProductInfo_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProductInfo): ProductInfo {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Order]): Order | null {
    return value.length === 0 ? null : from_candid_Order_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ProductInfo]): ProductInfo | null {
    return value.length === 0 ? null : from_candid_ProductInfo_n18(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ShippingAddress]): ShippingAddress | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Template]): Template | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _OrderStatus;
    total: bigint;
    paymentStatus: string;
    paymentMethod: string;
    userId: Principal;
    createdAt: bigint;
    estimatedDelivery: string;
    orderId: string;
    shippingAddress: _ShippingAddress;
    productionFileData: string;
    items: Array<_CartItem>;
}): {
    status: OrderStatus;
    total: bigint;
    paymentStatus: string;
    paymentMethod: string;
    userId: Principal;
    createdAt: bigint;
    estimatedDelivery: string;
    orderId: string;
    shippingAddress: ShippingAddress;
    productionFileData: string;
    items: Array<CartItem>;
} {
    return {
        status: from_candid_OrderStatus_n13(_uploadFile, _downloadFile, value.status),
        total: value.total,
        paymentStatus: value.paymentStatus,
        paymentMethod: value.paymentMethod,
        userId: value.userId,
        createdAt: value.createdAt,
        estimatedDelivery: value.estimatedDelivery,
        orderId: value.orderId,
        shippingAddress: value.shippingAddress,
        productionFileData: value.productionFileData,
        items: from_candid_vec_n15(_uploadFile, _downloadFile, value.items)
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customImageData: string;
    quantity: bigint;
    selectedSize: string;
    product: _ProductInfo;
}): {
    customImageData: string;
    quantity: bigint;
    selectedSize: string;
    product: ProductInfo;
} {
    return {
        customImageData: value.customImageData,
        quantity: value.quantity,
        selectedSize: value.selectedSize,
        product: from_candid_ProductInfo_n18(_uploadFile, _downloadFile, value.product)
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    imageData: string;
    name: string;
    description: string;
    dpiSettings: [] | [bigint];
    deliveryTime: string;
    sizeOptions: Array<string>;
    category: string;
    price: bigint;
    templateImageData: string;
}): {
    id: string;
    imageData: string;
    name: string;
    description: string;
    dpiSettings?: bigint;
    deliveryTime: string;
    sizeOptions: Array<string>;
    category: string;
    price: bigint;
    templateImageData: string;
} {
    return {
        id: value.id,
        imageData: value.imageData,
        name: value.name,
        description: value.description,
        dpiSettings: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.dpiSettings)),
        deliveryTime: value.deliveryTime,
        sizeOptions: value.sizeOptions,
        category: value.category,
        price: value.price,
        templateImageData: value.templateImageData
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    New: null;
} | {
    Printed: null;
} | {
    Delivered: null;
} | {
    Processing: null;
} | {
    Shipped: null;
}): OrderStatus {
    return "New" in value ? OrderStatus.New : "Printed" in value ? OrderStatus.Printed : "Delivered" in value ? OrderStatus.Delivered : "Processing" in value ? OrderStatus.Processing : "Shipped" in value ? OrderStatus.Shipped : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Order>): Array<Order> {
    return value.map((x)=>from_candid_Order_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CartItem>): Array<CartItem> {
    return value.map((x)=>from_candid_CartItem_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ProductInfo>): Array<ProductInfo> {
    return value.map((x)=>from_candid_ProductInfo_n18(_uploadFile, _downloadFile, x));
}
function to_candid_CartItem_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CartItem): _CartItem {
    return to_candid_record_n35(_uploadFile, _downloadFile, value);
}
function to_candid_OrderStatus_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): _OrderStatus {
    return to_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function to_candid_Order_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Order): _Order {
    return to_candid_record_n30(_uploadFile, _downloadFile, value);
}
function to_candid_ProductInfo_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductInfo): _ProductInfo {
    return to_candid_record_n37(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: OrderStatus;
    total: bigint;
    paymentStatus: string;
    paymentMethod: string;
    userId: Principal;
    createdAt: bigint;
    estimatedDelivery: string;
    orderId: string;
    shippingAddress: ShippingAddress;
    productionFileData: string;
    items: Array<CartItem>;
}): {
    status: _OrderStatus;
    total: bigint;
    paymentStatus: string;
    paymentMethod: string;
    userId: Principal;
    createdAt: bigint;
    estimatedDelivery: string;
    orderId: string;
    shippingAddress: _ShippingAddress;
    productionFileData: string;
    items: Array<_CartItem>;
} {
    return {
        status: to_candid_OrderStatus_n31(_uploadFile, _downloadFile, value.status),
        total: value.total,
        paymentStatus: value.paymentStatus,
        paymentMethod: value.paymentMethod,
        userId: value.userId,
        createdAt: value.createdAt,
        estimatedDelivery: value.estimatedDelivery,
        orderId: value.orderId,
        shippingAddress: value.shippingAddress,
        productionFileData: value.productionFileData,
        items: to_candid_vec_n33(_uploadFile, _downloadFile, value.items)
    };
}
function to_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customImageData: string;
    quantity: bigint;
    selectedSize: string;
    product: ProductInfo;
}): {
    customImageData: string;
    quantity: bigint;
    selectedSize: string;
    product: _ProductInfo;
} {
    return {
        customImageData: value.customImageData,
        quantity: value.quantity,
        selectedSize: value.selectedSize,
        product: to_candid_ProductInfo_n36(_uploadFile, _downloadFile, value.product)
    };
}
function to_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    imageData: string;
    name: string;
    description: string;
    dpiSettings?: bigint;
    deliveryTime: string;
    sizeOptions: Array<string>;
    category: string;
    price: bigint;
    templateImageData: string;
}): {
    id: string;
    imageData: string;
    name: string;
    description: string;
    dpiSettings: [] | [bigint];
    deliveryTime: string;
    sizeOptions: Array<string>;
    category: string;
    price: bigint;
    templateImageData: string;
} {
    return {
        id: value.id,
        imageData: value.imageData,
        name: value.name,
        description: value.description,
        dpiSettings: value.dpiSettings ? candid_some(value.dpiSettings) : candid_none(),
        deliveryTime: value.deliveryTime,
        sizeOptions: value.sizeOptions,
        category: value.category,
        price: value.price,
        templateImageData: value.templateImageData
    };
}
function to_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): {
    New: null;
} | {
    Printed: null;
} | {
    Delivered: null;
} | {
    Processing: null;
} | {
    Shipped: null;
} {
    return value == OrderStatus.New ? {
        New: null
    } : value == OrderStatus.Printed ? {
        Printed: null
    } : value == OrderStatus.Delivered ? {
        Delivered: null
    } : value == OrderStatus.Processing ? {
        Processing: null
    } : value == OrderStatus.Shipped ? {
        Shipped: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<CartItem>): Array<_CartItem> {
    return value.map((x)=>to_candid_CartItem_n34(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
